name: Documentation 
on:
  push: 
    branches: 
      - main 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Build documentation 
        run: |
          cd docs/
          make clean
          make html
      - name: Commit documentation changes to gh-pages
      run: |
        cd docs
        git clone https://github.com/ammsa23/colav.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        cp -r ../_build/html/* .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Upload documentation from latest commit"
      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "docs/gh-pages"

